services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci4_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    environment:
      - CI_ENVIRONMENT=development

  db:
    image: mysql:8.0
    container_name: ci4_db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sc_short_courses
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: ci_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d 

volumes:
  db_data: